spring:
  security:
    user:
      name: yingzuidou
      password: yingzuidou
server:
  port: 8084
# eureka集群信息
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://yingzuidou:yingzuidou@118.25.74.179:8085
