server:
  port: 8090
spring:
  application:
    name: platform-knowledge
eureka:
  client:
    serviceUrl:
      defaultZone: http://yingzuidou:yingzuidou@47.100.44.21:8084/eureka/, http://yingzuidou:yingzuidou@47.100.44.21:8085/eureka/
  instance:
    instance-id: platform-knowledge
    prefer-ip-address: true
    hostname: 47.98.215.5
    ip-address: 47.98.215.5

info:
  app.name: 'platform-knowledge'