server:
  port: 8086
spring:
  application:
    name: platform-zuul
eureka:
  client:
    serviceUrl:
      defaultZone: http://yingzuidou:yingzuidou@47.100.44.21:8084/eureka/, http://yingzuidou:yingzuidou@47.100.44.21:8085/eureka/
  instance:
    instance-id: platform-zuul
    prefer-ip-address: true
    hostname: localhost
    ip-address: localhost
zuul:
  prefix: /platform
  ignoredServices: '*'
  routes:
    blogService:
      path: /blog/**
      serviceId: platform-blog
      stripPrefix: false

feign:
  client:
    config:
      default:
        connectTimeout: 3000
        # 请求 超时时间
        readTimeout: 3000
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        timeout:
          # 是否开启超时熔断, 如果为false, 则熔断机制只在服务不可用时开启
          enabled: false
        isolation:
          strategy: SEMAPHORE
          # 配置hystrix熔断超时，它适用策略THREAD和SEMAPHORE
          thread:
            timeoutInMilliseconds: 5000

auth:
  serviceId: platform-blog
  token-header: x-client-token
  token-value: zuul-client-token
jwt:
  token-header: 'Authorization'
  token-header-prefix: 'Bearer-'
  # 单位为小时
  expire_token: 1
  # 单位为分
  refresh_token: 5
  issuer: 'platform_blog'
  subject: 'security_verify'
  secret: 'SHXIDEO#DK@jdj!8_88'