server:
  port: 8086
spring:
  application:
    name: platform-zuul
eureka:
  client:
    serviceUrl:
      defaultZone: http://yingzuidou:yingzuidou@47.100.44.21:8084/eureka/, http://yingzuidou:yingzuidou@47.100.44.21:8085/eureka/
  instance:
    instance-id: platform-zuul
    prefer-ip-address: true
    hostname: localhost
    ip-address: localhost
zuul:
  prefix: /platform
  ignoredServices: '*'
  routes:
    platform-knowledge: /knowledge/**
