server:
  port: 9092
  servlet:
    context-path: /blog
spring:
  application:
    name: platform-blog
  datasource:
    url: jdbc:mysql://118.25.74.179:3306/cms_web?useSSL=false
    username: root
    password: sgls652709
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  jpa:
    show-sql: true
logging:
  path: /usr/developer/backend/my_log
  level:
    root: INFO

eureka:
  client:
    serviceUrl:
      defaultZone: http://yingzuidou:yingzuidou@47.100.44.21:8084/eureka/, http://yingzuidou:yingzuidou@47.100.44.21:8085/eureka/
  instance:
    instance-id: platform-blog
    prefer-ip-address: true
    hostname: localhost
    ip-address: localhost

