server:
  port: 8085
eureka:
  instance:
    hostname: 47.100.44.21
    ip-address: 47.100.44.21
  client:
    registerWithEureka: false #不需要注册到注册中心
    fetchRegistry: false #不需要从注册中心拉取服务
    serviceUrl:
      defaultZone: http://47.100.44.21:8084

spring:
  application:
      name: platform-eureka-service
  security:
    user:
      name: yingzuidou
      password: yingzuidou
