server:
  port: 9091
  servlet:
    context-path: /cms_web
spring:
  application:
    name: platform-developer
logging:
  path:  /home/platform/platform-backend-site/logs
  level:
    root: ERROR
    org:
      springframework:
        web: ERROR
      hibernate: ERROR
      yingzuidou:
        platform: ERROR

eureka:
  client:
    serviceUrl:
      defaultZone: http://yingzuidou:yingzuidou@106.13.166.145:8084/eureka/, http://yingzuidou:yingzuidou@106.13.166.145:8085/eureka/
  instance:
    instance-id: platform-developer
    prefer-ip-address: true
    hostname: 106.13.167.135
    ip-address: 106.13.167.135

skip:
  login:
    url: /login/login.do