server:
  port: 8086
spring:
  application:
    name: platform-zuul
eureka:
  client:
    serviceUrl:
      defaultZone: http://yingzuidou:yingzuidou@47.100.44.21:8084/eureka/, http://yingzuidou:yingzuidou@47.100.44.21:8085/eureka/

zuul:
  prefix: /platform # 增加request访问前缀
  ignoredServices: '*' # 忽略request的指定服务名，例如eureka的服务名不能访问，ignoredServices: 'PRODUCE',如果所有eureka服务名忽略，那么用*就可以完成，只有下面指定的才能访问
  routes: # 如果不加下面的映射，那么在前端只能访问eureka中的服务名，这样会暴露eureka中的服务名信息
    platform-knowledge: /produce/** # eureka的produce路由请求url