server:
  port: 8085
eureka:
  instance:
    hostname: 118.25.74.179
    ip-address: 118.25.74.179
  client:
    registerWithEureka: false #不需要注册到注册中心
    fetchRegistry: false #不需要从注册中心拉取服务
    serviceUrl:
      defaultZone: http://118.25.74.179:8084

spring:
  application:
    name: platform-eureka-service-peer
  security:
    user:
      name: yingzuidou
      password: yingzuidou
