server:
  port: 8086
spring:
  application:
    name: platform-zuul
eureka:
  client:
    serviceUrl:
      defaultZone: http://yingzuidou:yingzuidou@47.100.44.21:8084/eureka/, http://yingzuidou:yingzuidou@47.100.44.21:8085/eureka/
  instance:
    instance-id: platform-zuul
    prefer-ip-address: true
    hostname: localhost
    ip-address: localhost
zuul:
  prefix: /platform
  ignoredServices: '*'
  routes:
    platform-knowledge: /knowledge/**
feign:
  hystrix:
    enabled: true

auth:
  serviceId: platform-developer
jwt:
  token-header: 'Authorization'
  token-header-prefix: 'Bearer-'
  # 单位为小时
  expire_token: 1
  # 单位为分
  refresh_token: 5
  issuer: 'platform_blog'
  subject: 'security_verify'
  secret: 'SHXIDEO#DK@jdj!8_88'