server:
  port: 9093
  servlet:
    context-path: /frontend
spring:
  jackson:
    date-format:
      yyyy-MM-dd
    time-zone:
      GMT+8
  application:
    name: platform-frontend-site
  datasource:
    url: jdbc:mysql://118.25.74.179:3306/cms_web?useSSL=false
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  jpa:
    show-sql: true
  resources:
    # 参考https://www.cnblogs.com/pomer-huang/archive/2018/09/12/pomer.html
    # 在SpringBoot中的classpath指的是resources以及java等根目录 classpath:/resources 这种写法特别让人困惑
    # 他指的是resources目录下的resources
    static-locations: classpath:/, classpath:/static/, file:D://cover-upload, file:/home/platform/platform-frontend/resources
  mvc:
    static-path-pattern: '/static/**'

auth:
  serviceId: platform-frontend-site
  token-header: x-client-token
  token-value: zuul-client-token
jwt:
  token-header: 'Authorization'
  token-header-prefix: 'Bearer-'
  # 单位为小时
  expire_token: 600
  # 单位为分
  refresh_token: 5
  issuer: 'platform_blog'
  subject: 'security_verify'
  secret: 'SHXIDEO#DK@jdj!8_88'

static:
  resource:
    uploadPath: '/home/platform/platform-frontend/resources'
    accessUrl: 'http://47.98.215.5:8086/platform/frontend/static/'
github:
  clientId: '47fca5d6cdbf13ae8984'
  clientSecret: 'c1f7002ed74ed439ebe8d8e238263e945d028f90'
  frontendUrl: 'http://47.98.215.5'
logging:
  path:  /home/platform/platform-frontend/logs
  level:
    root: ERROR

eureka:
  client:
    serviceUrl:
      defaultZone: http://yingzuidou:yingzuidou@118.25.74.179:8084/eureka/, http://yingzuidou:yingzuidou@118.25.74.179:8085/eureka/
  instance:
    instance-id: platform-frontend-site
    prefer-ip-address: true
    hostname: 47.98.215.5
    ip-address: 47.98.215.5

info:
  app.name: 'platform-frontend'
  app.descr: '博客前台网站'