server:
  port: 9091
  servlet:
    context-path: /cms_web
spring:
  application:
    name: platform-developer
  datasource:
    url: jdbc:mysql://rm-wz9hw0a1qwbj5vywfmo.mysql.rds.aliyuncs.com:3306/cms_web?useSSL=false
    username: root
    password: ShangGuanls@123
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  jpa:
    show-sql: true
logging:
  path:  /home/platform/platform-backend-site/logs
  level:
    root: ERROR
    org:
      springframework:
        web: ERROR
      hibernate: ERROR
      yingzuidou:
        platform: ERROR

eureka:
  client:
    serviceUrl:
      defaultZone: http://yingzuidou:yingzuidou@106.13.166.145:8084/eureka/, http://yingzuidou:yingzuidou@106.13.166.145:8085/eureka/
  instance:
    instance-id: platform-developer
    prefer-ip-address: true
    hostname: 106.13.167.135
    ip-address: 106.13.167.135

skip:
  login:
    url: /login/login.do