server:
  port: 8086
spring:
  application:
    name: platform-zuul
eureka:
  client:
    serviceUrl:
      defaultZone: http://yingzuidou:yingzuidou@47.100.44.21:8084/eureka/, http://yingzuidou:yingzuidou@47.100.44.21:8085/eureka/
  instance:
    instance-id: platform-zuul
    prefer-ip-address: true
    hostname: localhost
    ip-address: localhost
zuul:
  # zuul转发请求会过滤默认的请求头，例如Authorization,这里使用sensitive-headers清空默认请求头
  sensitive-headers:
  prefix: /platform
  ignoredServices: '*'
  routes:
    blogService:
      path: /blog/**
      serviceId: platform-blog
      stripPrefix: false
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000

# 单独给platform-blog配置超时，需要配置ribbon超时，否则出现问题:https://segmentfault.com/q/1010000019700014
platform-blog:
  ribbon:
    ConnectTimeout: 60000
    ReadTimeout: 60000

feign:
  client:
    config:
      default:
        connectTimeout: 60000
        # 请求 超时时间
        readTimeout: 60000
  hystrix:
    enabled: false

hystrix:
  command:
    default:
      execution:
        timeout:
          # 是否开启超时熔断, 如果为false, 则熔断机制只在服务不可用时开启
          enabled: false
        isolation:
          strategy: SEMAPHORE
          # 配置hystrix熔断超时，它适用策略THREAD和SEMAPHORE
          thread:
            timeoutInMilliseconds: 60000

auth:
  serviceId: platform-blog
  token-header: x-client-token
  token-value: zuul-client-token
jwt:
  token-header: 'Authorization'
  token-header-prefix: 'Bearer-'
  # 单位为小时
  expire_token: 1
  # 单位为分
  refresh_token: 5
  issuer: 'platform_blog'
  subject: 'security_verify'
  secret: 'SHXIDEO#DK@jdj!8_88'