server:
  port: 9092
  servlet:
    context-path: /blog
spring:
  jackson:
    date-format:
      yyyy-MM-dd
    time-zone:
      GMT+8
  application:
    name: platform-blog
  datasource:
      url: ENC(J5qwWRUdfFDDrQHb08byXEW2zyvPmK3y81OztJ6pFFMNVs7ziYDOVWnnF2ve9vGWbYTlAy0E674+xWjNuEjpZnEwGNTJDm8J3KdQ0gH2YTU+U+oGPjTjRPlnd7qmnjAT)
      username: ENC(NeVfH7knihIrJJoYcrRb2w==)
      password: ENC(uA8SfeLnpuk+hObYAXYG2MYdN162PCst)
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  jpa:
    show-sql: true
  resources:
    # 参考https://www.cnblogs.com/pomer-huang/archive/2018/09/12/pomer.html
    # 在SpringBoot中的classpath指的是resources以及java等根目录 classpath:/resources 这种写法特别让人困惑
    # 他指的是resources目录下的resources
    static-locations: classpath:/, classpath:/static/, file:/home/platform/resources
  mvc:
    static-path-pattern: '/static/**'

auth:
  serviceId: platform-blog
  token-header: x-client-token
  token-value: zuul-client-token
jwt:
  token-header: 'Authorization'
  token-header-prefix: 'Bearer-'

static:
  resource:
    # 使用docker部署下面文件的路径是存放在docker容器里面，当实例重新创建是图片资源丢失，所以需要一个docker做映射 
    uploadPath: '/home/platform/resources'
    accessUrl: 'http://106.13.166.145:8086/platform/blog/static/'

logging:
  path: /home/platform/logs
  level:
    root: ERROR
    org:
      springframework:
        web: ERROR
      hibernate: ERROR
      yingzuidou:
        platform: ERROR
jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}
eureka:
  client:
    serviceUrl:
      defaultZone: http://yingzuidou:yingzuidou@106.13.166.145:8084/eureka/, http://yingzuidou:yingzuidou@106.13.166.145:8085/eureka/
  instance:
    instance-id: platform-blog
    prefer-ip-address: true
    hostname: 47.100.44.21
    ip-address: 47.100.44.21

info:
  app.name: 'platform-blog'
  app.descr: '博客工作台'
